---
- name: Ensure US locale exists
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Set hostname to inventory hostname
  hostname: name={{inventory_hostname}}

- name: Update apt cache and upgrade
  apt:
    update_cache: yes
    upgrade: yes

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
